# Generated by Django 5.0.2 on 2024-02-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='open',
            field=models.BooleanField(choices=[(1, '공개'), (0, '비공개')], default=1),
        ),
    ]
