# Generated by Django 5.0.2 on 2024-02-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0002_alter_reply_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='group_number',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='open',
        ),
        migrations.AddField(
            model_name='reply',
            name='group_id',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_depth',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_private_status',
            field=models.BooleanField(choices=[(True, '비밀 댓글'), (False, '일반 댓글')], default=1),
        ),
    ]
